version: '3.4'

services:
  webapplication1:
    image: ${DOCKER_REGISTRY-}webapplication1
    build:
      context: .
      dockerfile: WebApplication1/Dockerfile
    links:
      - redis
      - mssql
  redis:
    image: redis
    volumes:
      - ./redis/data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    restart: always
  mssql:
    image: microsoft/mssql-server-linux:latest
    restart: always
    command: "sh -c '/init/start-up.sh & /opt/mssql/bin/sqlservr;'"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=seigi@123
      - MSSQL_PID=Express
      - MSSQL_LCID=1041
      - MSSQL_COLLATION=Japanese_CI_AS
    ports:
      - 1433:1433
    volumes:
      #- ./mssql/mssql-db:/var/opt/mssql
      - ./mssql/init:/init

volumes:
  mssql-data:
    driver: local