version: '3.4'

services:
  webapplication1:
    image: ${DOCKER_REGISTRY-}webapplication1
    build:
      context: .
      dockerfile: WebApplication1/Dockerfile
    ports:
      - "5000:5000"
    links:
      - redis
      - mssql
  redis:
    image: redis
    volumes:
      - ./redis/data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    restart: always
  mssql:
    image: microsoft/mssql-server-linux:2017-latest
    volumes:
      - mssql-data:/var/opt/mssql/
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: seigi@123
    ports:
      - "1433:1433"

volumes:
  mssql-data:
    driver: local